<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nw_todos"
 *
 * Auto generated by Extension Builder 2019-04-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Todos Listing',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Ning Wei',
    'author_email' => 'ning.wei@int-trade.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
